### ISSUE TITLE
Error for resolving dependency com.crygier:graphql-jpa v.0.3-SNAPSHOT

### ISSUE THREAD

**Issue by isdzulqor** [timtebeek/graphql-jpa-spring-boot-starter#1]
I have cloned your project and try to import in my IDE. but an issue came to me. I could not resolve my dependency for com.crygier:graphql-jpa v.0.3-SNAPSHOT. Any solution for this issue will be helpful so much. Thank you

**Comment by timtebeek** [comment]
Hi! Have a look at: https://github.com/jcrygier/graphql-jpa
You'll want to install a local version of the master branch, which should match 0.3-snapshot. Only once that upstream project performs a release can I update my dependency, so sorry about the slight inconvenience until then.

**Comment by isdzulqor** [comment]
sorry to say this, but your project is still full of error. You did not include dependency of spring boot and jpa in pom. and when I try to run by firstly creating class where the main method inside it. but still full of error. may be u can make a documentation how to work with ur project.

**Comment by timtebeek** [comment]
Traveling right now.. I'll return March 6th. Until then I'm without a PC.

Downside currently is that I depend on a snapshot version of the library
you found, so if you can get him to do a release then you can upgrade the
dependency to the new version.

**Comment by timtebeek** [comment]
Following jcrygier/graphql-jpa#20 I've been able to address most of your issues in 438101ae2a4ea2bd5f36d4d7dc90424067504f1c.

If you would still like me to expand the documentation please let me know. By now you should just be able to add the starter as a dependency without any further tweaks get a functioning graphql endpoint.
